[package]
name = "olive3d"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.20.0"
lazy_static = "1.5.0"
rand = "0.8.5"
sdl2 = "0.37.0"

[features]
default = ["sdl"]
sdl = []
term = []
wasm = []
